Vagrant.configure("2") do |config|

    config.vm.define "vm1" do |vm1|
      vm1.vm.box = "ubuntu/xenial64"
      vm1.vm.hostname = 'vm1'
      vm1.vm.network "private_network", ip: "192.168.3.1"
  
      ### config.vm.synced_folder "/home/raghav/Desktop/vagrant/a/sync", "/home", :nfs => {:mount_options => ["dmode=777", "fmode=666"]}
     
      vm1.vm.provider "virtualbox" do |vb|
        # Display the VirtualBox GUI when booting the machine
        #vb.gui = true
      
        # Customize the amount of memory on the VM:
        vb.memory = "3072"
        vb.cpus = 3
      end
  
      # config.vm.provision "shell", inline: <<-SHELL
      #   apt-get update
      #   apt-get install -y apache2
      # SHELL
  
      vm1.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/me.pub"
      vm1.vm.provision "shell", path: "bootstrap.sh"
    end
  
    config.vm.define "vm2" do |vm2|
      vm2.vm.box = "ubuntu/xenial64"
      vm2.vm.hostname = 'vm2'
      vm2.vm.network "private_network", ip: "192.168.3.2"
  
      ### config.vm.synced_folder "/home/raghav/Desktop/vagrant/a/sync", "/home", :nfs => {:mount_options => ["dmode=777", "fmode=666"]}
     
      vm2.vm.provider "virtualbox" do |vb|
        # Display the VirtualBox GUI when booting the machine
        #vb.gui = true
      
        # Customize the amount of memory on the VM:
        vb.memory = "3072"
        vb.cpus = 3
      end
  
      # config.vm.provision "shell", inline: <<-SHELL
      #   apt-get update
      #   apt-get install -y apache2
      # SHELL
  
      vm2.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/me.pub"
      vm2.vm.provision "shell", path: "bootstrap.sh"
    end
  
  end
  